### ISSUE TITLE
Start Game

### ISSUE THREAD

**Issue by BenjaminHac-Edu** [SE2Project-BHKPTZ/frontend#37]
The game should start when the lobby administrator clicks the Start button.

## Definition of done

- [x] the game activity should be seen when the 'Start' button is clicked and there are enough players (3-6) in the lobby
- [x] if there are not enough players (1 or 2), an error message should be displayed to the admin
- [x] each player should see their own hands
- [x] the logic (start game, start round, get Cards) is handled by the backend

**Comment by TannerGabriel** [comment]
Closed via #42
