### ISSUE TITLE
Create sketches for main screens

### ISSUE THREAD

**Issue by TannerGabriel** [SE2Project-BHKPTZ/frontend#4]
We should create some first sketches for the application's main screens and visualize the user flow and interaction. For this ticket, it might be necessary to research the game functionality of "Wizard" in more detail.

## Definition of done

- [x] Basic sketches for the main screens/activities
- [x] User flow (either included in the sketches or using a flow diagram)
- [x] (Optional) Collect color theme ideas 

The results of this ticket should either be documented in the ticket or shared internally.

**Comment by BenjaminHac-Edu** [comment]
I made the sketches in Drawio.
Here is the link to see the current status: https://drive.google.com/file/d/1R_gunTVyYfi6sJ6QcXrO5VvKsY6urfvH/view?usp=sharing

Feedback also welcome

**Comment by BenjaminHac-Edu** [comment]
![Image](https://github.com/SE2Project-BHKPTZ/frontend/assets/161861890/517d3c75-8614-4453-a828-010be7c5e306)
